name: Nightly Unstable Build and Package

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  call-unstable-build:
    uses: redis/redis-rpm/.github/workflows/publish_unstable_package.yaml@unstable
